# Default settings and matrix for amd64 jobs (except Python 3.7)
os: linux
dist: focal
arch: amd64
language: python
cache:
  pip: true
  directories:
    - .tox
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "3.9"
  - "3.10"
  - "3.11-dev"
install: pip install tox-travis
script: tox

# Adjustments for specific platforms
jobs:
  include:
    # Python 3.7 has numpy install failures on amd64
    # Add job explicitly with adjustment of install script
    # Also use this job to test the docs build
    - name: amd64 / Python 3.7 / numpy 1.16-1.21 & docs
      arch: amd64
      python: "3.7"
      install: pip install --upgrade importlib_metadata tox-travis
      script: tox -e "py37-numpy{1.16,1.17,1.18,1.19,1.20,1.21},docs"

    # ARM
    - arch: arm64
      python: "2.7"
      dist: xenial
    - arch: arm64
      python: "3.6"
    - arch: arm64
      python: "3.7"
    - arch: arm64
      python: "3.8"
    - arch: arm64
      python: "3.9"
    - arch: arm64
      python: "3.10"

    # PPC
    - arch: ppc64le
      python: "2.7"
      dist: xenial
    - arch: ppc64le
      python: "3.6"
    - arch: ppc64le
      python: "3.7"
      # Build up to the full range of numpy versions
      script: tox -e "py37-numpy{1.16,1.17,1.18}"
    - arch: ppc64le
      python: "3.8"
      # Build up to the full range of numpy versions
      script: tox -e "py38-numpy{1.17,1.18,1.19}"
    - arch: ppc64le
      python: "3.9"
      # Build up to the full range of numpy versions
      script: tox -e "py39-numpy{1.19,1.20,1.21}"
    - arch: ppc64le
      python: "3.10"

    # s390x build image has a pip cache permissions problem (except for Python 2.7)
    # List all s390x jobs explicitly with adjusted install scripts
    - arch: s390x
      python: "2.7"
      dist: xenial
    - arch: s390x
      python: "3.6"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels || true
        - pip install tox-travis
    - arch: s390x
      python: "3.7"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels || true
        - pip install tox-travis
    - arch: s390x
      python: "3.8"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels || true
        - pip install tox-travis
    - arch: s390x
      python: "3.9"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels || true
        - pip install tox-travis
    - arch: s390x
      python: "3.10"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels || true
        - pip install tox-travis

    # Mac build
    - name: osx / Python 2.7 and 3.7
      os: osx
      language: generic
      install: pip2 install tox
      script: tox --skip-missing-interpreters
