os: linux
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
jobs:
  include:
    - language: generic
      os: osx
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  allow_failures:
    - arch: arm64
install: pip install tox-travis
script: tox
