# Matrix for standard jobs
os: linux
arch:
  - amd64
  - arm64
  - ppc64le
language: python
cache: pip
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox

# Adjustments for specific platforms
jobs:
  include:
    # Python 3.7 has numpy install failures on amd64
    # Add all Python 3.7 jobs explicitly with adjustment of install script for amd64
    - arch: amd64
      cache: pip
      python: "3.7"
      install: pip install --upgrade importlib_metadata tox-travis
    - arch: arm64
      python: "3.7"
    - arch: ppc64le
      cache: pip
      python: "3.7"
    # s390x build image has a pip cache permissions problem (except for Python 2.7)
    # List all s390x jobs explicitly with adjusted install scripts
    - arch: s390x
      cache: pip
      python: "2.7"
      install: pip install tox-travis
    - arch: s390x
      cache: pip
      python: "3.6"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels
        - pip install tox-travis
    - arch: s390x
      cache: pip
      python: "3.7"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels
        - pip install tox-travis
    - arch: s390x
      cache: pip
      python: "3.8"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels
        - pip install tox-travis
    - arch: s390x
      cache: pip
      python: "3.9"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels
        - pip install tox-travis
    # Mac build
    - os: osx
      language: generic
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  # Allow failures on ARM because numpy 1.18 fails to install properly
  allow_failures:
    - arch: arm64
