# Matrix for standard jobs
os: linux
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "2.7"
  - "3.6"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox

# Adjustments for specific platforms
jobs:
  include:
    - arch: amd64
      python: "3.7"
      install: pip install --upgrade importlib_metadata tox-travis
    - arch: arm64
      python: "3.7"
    - arch: ppc64le
      python: "3.7"
    - arch: s390x
      python: "3.7"
      install:
        - sudo chown -Rv $(id -u):$(id -g) ~/.cache/pip/wheels
        - ls -l /home/travis/.cache/pip
        - ls -l /home/travis/.cache/pip/wheels
        - pip install tox-travis
    - os: osx
      language: generic
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  # Allow failures on ARM because numpy 1.18 fails to install properly
  allow_failures:
    - arch: arm64
