# Matrix for standard jobs
os: linux
arch:
  - amd64
  - arm64
  - ppc64le
  - s390x
language: python
python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
install: pip install tox-travis
script: tox

# Adjustments for specific platforms
jobs:
  include:
    - arch: amd64
      python: "3.7"
      install: pip install importlib_metadata tox-travis
    - language: python
      os: osx
      install: pip2 install tox-travis
      script: tox --skip-missing-interpreters
  # Allow failures on ARM because numpy 1.18 fails to install properly
  allow_failures:
    - arch: arm64
