[build-system]
requires = ["setuptools>=77.0"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["mrcfile"]
package-dir = {"" = "src"}

[tool.setuptools.dynamic]
version = {attr = "mrcfile.version.__version__"}
readme = {file = ["README.rst"]}

[project]
name = "mrcfile"
authors = [
    {name = "Colin Palmer", email = "colin.palmer@stfc.ac.uk"},
]
dynamic = ["version", "readme"]
description = "MRC file I/O library"
license = "BSD-3-Clause"
license-files = ["LICENSE.txt"]
requires-python = ">=3.9"
classifiers = [
    'Development Status :: 5 - Production/Stable',
    'Intended Audience :: Developers',
    'Intended Audience :: Science/Research',
    'Natural Language :: English',
    'Operating System :: OS Independent',
    'Programming Language :: Python',
    'Programming Language :: Python :: 3.9',
    'Programming Language :: Python :: 3.10',
    'Programming Language :: Python :: 3.11',
    'Programming Language :: Python :: 3.12',
    'Programming Language :: Python :: 3.13',
    'Topic :: Scientific/Engineering :: Bio-Informatics',
    'Topic :: Software Development :: Libraries :: Python Modules'
]
dependencies = ["numpy >= 1.16.0"]

optional-dependencies.dev = [
    "pre-commit",
    "pytest",
    "ruff",
]

[project.urls]
homepage = "https://github.com/ccpem/mrcfile"
documentation = "https://mrcfile.readthedocs.io/"

[project.scripts]
'mrcfile-header' = 'mrcfile.command_line:print_headers'
'mrcfile-validate' = 'mrcfile.validator:main'

[tool.ruff]
# Same as Black.
line-length = 88
indent-width = 4

target-version = "py39"

[tool.ruff.lint]
# Linting rules
select = [
    "A",  # flake8-builtins
    "ARG",  # Unused arguments
    "ASYNC",  # flake8-async
    "B",  # flake8-bugbear
    "BLE",  # Overly-broad except clauses
    "C4",  # flake8-comprehensions
    "C901",  # McCabe complexity
    "COM",  # flake8-commas
    "D1",  # Missing docstrings in public API
    "E",  # pycodestyle errors
    "ERA",  # Eradicate commented-out code
    "EXE",  # flake8-executable
    "F",  # Pyflakes
    "FA",  # flake8-future-annotations
    "FBT",  # Avoid positional boolean arguments
    "FIX",  # flake8-fixme
    "FLY",  # flynt
    "FURB",  # refurb
    "I",  # isort
    "ICN",  # flake8-import-conventions
    "ISC",  # Implicit string concatenation
    "N",  # PEP8 naming conventions
    "NPY",  # NumPy-specific rules
    "PERF",  # Perflint
    "PGH",  # pygrep-hooks (incl no bare "noqa" or "type: ignore" comments)
    "PIE",  # flake8-pie
    "PL",  # Pylint
    "Q",  # flake8-quotes
    "RSE",  # flake8-raise
    "RUF",  # Ruff-specific rules
    "S",  # flake8-bandit
    "SIM",  # flake8-simplify
    "SLF",  # flake8-self
    "SLOT", # flake8-slots
    "T10",  # flake8-debugger
    "T20",  # flake8-print
    "TD",  # flake8-todos
    "TID",  # flake8-tidy-imports
    "TRY",  # tryceratops
    "UP",  # pyupgrade
    "W",  # pycodestyle warnings
]
# Possibly useful but not yet selected: ANN, DTZ, EM, LOG, G, TC, D[234]

# Specific rules to ignore
ignore = [
    "B028",  # explicit stacklevel keyword in warnings - aim to review these
    "COM812",  # trailing commas - won't fix, conflicts with Ruff formatter
    "PLR2004",  # magic values - won't fix, not worth changing these
    "TRY003",  # long exception messages - won't fix
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

[tool.ruff.lint.per-file-ignores]
# Ignore some rules that are not relevant to test code
"tests/**.py" = [
    "D",  # docstrings
    "S101",  # assertions
    "SLF001",  # private member access
    "T20",  # flake8-print
]

# Ignore some rules that are not relevant to docs config file
"docs/conf.py" = [
    "D"  # docstrings
]
