# Config file for tox
[tox]
envlist =
    py3.9-numpy{1.19,1.20,1.21,1.22,1.23,1.24,1.25,1.26,2.0},
    py3.10-numpy{1.22,1.23,1.24,1.25,1.26,2.0,2.1,2.2},
    py3.11-numpy{1.23,1.24,1.25,1.26,2.0,2.1,2.2,2.3,2.4},
    py3.12-numpy{1.26,2.0,2.1,2.2,2.3,2.4},
    py3.13-numpy{2.1,2.2,2.3,2.4},
    py3.14-numpy{2.3,2.4},
    py3.12-docs

# matrix of test environments
[testenv]
deps =
    mypy == 1.16.0
    pytest
    numpy1.19: numpy >= 1.19.0, < 1.20.0
    numpy1.20: numpy >= 1.20.0, < 1.21.0
    numpy1.21: numpy >= 1.21.0, < 1.22.0
    numpy1.22: numpy >= 1.22.0, < 1.23.0
    numpy1.23: numpy >= 1.23.0, < 1.24.0
    numpy1.24: numpy >= 1.24.0, < 1.25.0
    numpy1.25: numpy >= 1.25.0, < 1.26.0
    numpy1.26: numpy >= 1.26.0, < 1.27.0
    numpy2.0: numpy >= 2.0.0, < 2.1.0
    numpy2.1: numpy >= 2.1.0, < 2.2.0
    numpy2.2: numpy >= 2.2.0, < 2.3.0
    numpy2.3: numpy >= 2.3.0, < 2.4.0
    numpy2.4: numpy >= 2.4.0, < 2.5.0
commands =
    pytest
    mypy --no-incremental

# Ignore missing imports because numpy 1.19 didn't have type hints
[testenv:py3.9-numpy1.19]
commands =
    pytest
    mypy --no-incremental --ignore-missing-imports

# Ignore arg-type to avoid an erroneous type error that only appears in py3.9-numpy1.20
[testenv:py3.9-numpy1.20]
commands =
    pytest
    mypy --no-incremental --disable-error-code arg-type

# Test html build and doctests
[testenv:py3.12-docs]
platform = linux
changedir = docs
deps = -rdocs/requirements.txt
commands=
    sphinx-build -W -n -b html -d {envtmpdir}/doctrees .  {envtmpdir}/html
    sphinx-build -W -n -b doctest -d {envtmpdir}/doctrees .  {envtmpdir}/doctest
